import type { Metadata } from "next";
import { Cormorant_Garamond, Geist_Mono } from "next/font/google";
import "./globals.css";

const cormorantGaramond = Cormorant_Garamond({
  subsets: ['latin'],
  weight: ['400', '700'],
  style: ['normal', 'italic'], 
  variable: '--font-cormorant',
});

const geist = Geist_Mono({
  subsets: ['latin'],
  weight: ['400', '500', '700'], 
  variable: '--font-geist'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en" className="h-full antialiased">
      <body className={`${cormorantGaramond.variable} ${geist.variable} min-h-full flex flex-col`}>
        {children}
      </body>
    </html>
  );
}
